### ISSUE TITLE
Need 3D settings control

### ISSUE THREAD

**Issue by ianneilmacleod** [GeosoftInc/gxapi#12]
https://github.com/GeosoftInc/gxpy/issues/58

**Comment by charliecq** [comment]
I added render mode setter/getter for VOXD in master branch:
SetRenderMode_VOXD, GetRenderMode_VOXD

**Comment by ianneilmacleod** [comment]
@charliecq we need to add these two functions to https://github.com/GeosoftInc/gxapi/blob/master/spec/core/VOXD.py

I believe these are auto-generated. @jbgeosoft should be able to show you how to update this in this repo.

**Comment by charlieqc** [comment]
@ianneilmacleod The 2 functions are already available in 
https://github.com/GeosoftInc/gxapi/blob/master/spec/core/VOXD.py

**Comment by ianneilmacleod** [comment]
get/set_render_mode implemented in 9.5

**Comment by ianneilmacleod** [comment]
@charlieqc reopened to let you sort out a possibly related issue.

Test the VOXD api from gxpy by running: https://github.com/GeosoftInc/gxpy/blob/master/geosoft/gxpy/tests/test_vox_display.py

if run from python (I'm using 3.6) the program stops before terminating normally:
![image](https://user-images.githubusercontent.com/6362663/45180353-2ae5ce00-b1e9-11e8-8ffb-c631ab307625.png)

Run from pycharm, which is my normal test environment, Python crashed with an error:

![image](https://user-images.githubusercontent.com/6362663/45180440-684a5b80-b1e9-11e8-9994-745b50dbe8fe.png)

In the past these errors were triggered by a Geosoft assertion, which we need to find and correct, but with this edition of 9.5 the system just stops (no assertion or abort.log).

Debug by running from your IDE and step into Geosoft code and follow the path to failure.

**Comment by ianneilmacleod** [comment]
closed by mistake - see my last comment on current failure.

**Comment by ianneilmacleod** [comment]
@charlieqc AND the constants are wrong.  They should be:

gxapi.VOXELRENDER_FILL = 0
gxapi.VOXELRENDER_EDGES = 1
gaxpi.VOXELRENDER_FILL_EDGES = 2
gxapi.VOXELRENDER_SMOOTH = 3

This should have been tested before getting to me - we can chat about that.

**Comment by charlieqc** [comment]
@ianneilmacleod Thanks for pointing out the wrong constants. I noticed that the render mode enums located in m:\core\source\geoengine.map\geoengine.map\include\voxd.h are
enum VOXEL_RENDER {
   VOXEL_RENDER_PIECEWISE = 0,
   VOXEL_RENDER_PIECEWISE_WIREFRAME_ONLY,
   VOXEL_RENDER_PIECEWISE_WIREFRAME,
   VOXEL_RENDER_TRILINEAR,
   VOXEL_RENDER_TRILINEAR_WIREFRAME_ONLY,
   VOXEL_RENDER_TRILINEAR_WIREFRAME
};
Should I export all of them to spec/core/VOXD.py and give the same name pattern as in voxd.h?

**Comment by jbgeosoft** [comment]
@charlieqc, the enums you added was based on the old Voxel rendering modes, before we introduced smooth shader based interpolation rendering. Did you see those somewhere else? Since we should probably eliminate them from the core code.

That being said we might want to consider emulating the UI on the GX API level since it is really 3 display modes as before (although not the same 3 modes), i.e: FILL, EDGES and FILL_WITH_EDGES along with a bool to enable SMOOTH (tri-linear interpolation).

Either would work though, it should just be documented int the Constant and Define specs. I notice your commit was a little light on docs in that region.

**Comment by charlieqc** [comment]
@jbgeosoft You can find the same rendering modes in spec/core/SURFACEITEM.py, the corresponding enums are located in m:\core\source\geoengine.map\geoengine.map\include\geosurfaced.h
Do you know where I can find some detailed descriptions for the modes so I can put them into Define spec?

**Comment by jbgeosoft** [comment]
Yes, surface and voxel rendering modes are different. I see the documentation for these are also a bit light (non-existing) in the core headers. Sergei is the one that can probably explain them best, but it comes down to what I explained above. We do not need to heavily document heavily, a simple sentence what flat, edges and fill with edges means and that enabling tri-linear will give a smooth interpolated rendering of the voxel should suffice. You can also find a lot of details on the rendering changes in our internal wiki at 'Notes and Questions on the New Voxel Rendering Engine'

**Comment by ianneilmacleod** [comment]
@charliecq @jbgeosoft , perhaps consider bools for all at the API level? Fill, Edges, Smooth, each of which can be True or False, default being Fill == True. This seems the simplest and most consistent API to me. Something like:

set_render_mode(fill_bool, edge_book, smooth_bool)
get_render_mode(fill_bool, edge_bool, fill_bool)

Just a thought. In gxpy we will likely make these properties of the VOXD instance in any case, and we can marshal across to however you do this in GXAPI.

**Comment by charlieqc** [comment]
The VOXD constants are now update with right value and simple comments. I invoked the render mode setter/getter in my own simple test and it worked.

**Comment by GeoTPop** [comment]
@ianneilmacleod said:

> @charliecq @jbgeosoft , perhaps consider bools for all at the API level? Fill, Edges, Smooth, each of which can be True or False, default being Fill == True. This seems the simplest and most consistent API to me. 

If all of these options are bools and all are false, then the object will not be rendered.  We struggled with this in the GUI before settling on radio buttons.
Also, as of 9.5, the voxel and surface rendering options in the UI will be the same.  Sergei will be able to tell you about the implementation.

**Comment by ianneilmacleod** [comment]
Verified fixed by 9.5 build 20181017.33
