### ISSUE TITLE
Running out of GXAPI resources.

### ISSUE THREAD

**Issue by ianneilmacleod** [GeosoftInc/gxapi#18]
@RogerAmorim 
Reference conversation: https://geosoft.vanillaforums.com/discussion/1195/gxerror-attempting-to-load-too-many-resources#latest

Can we increase MAX_RESOURCES (see gxp/gxp.ih)?  It is currently set to 2048, but with 64-bit memory I suggest we can rethink this maximum.Perhaps make it 8 times bigger?

It is likely worth review all the settings in gxp.ih.

**Comment by charliecq** [comment]
MAX_RESOURCES in gxp.h has been increased to 16384(8 times) and now works well in my own test. 
[test.py.txt](https://github.com/GeosoftInc/gxapi/files/2146357/test.py.txt)

**Comment by ianneilmacleod** [comment]
ok for 9.5
